[project]
name = "computer-vision-playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "easyocr>=1.7.0",
    "matplotlib>=3.10.8",
    "opencv-python>=4.8.0",
    "pyside6>=6.10.1",
    "watchfiles>=1.1.1",
]
